### ISSUE TITLE
Support all assignment operators

### ISSUE THREAD

**Issue by lucasefe** [lucasefe/eslint-plugin-align-assignments#2]
Operators like `= += -= *= /= %= <<= >>= >>>= &= ^= \|=` should be valid assignment operators, and the plugin should be able to align them properly. 

Suggestion of what would be valid. 
```
a   *= 3;
b  >>= 3;
f >>>= 3;
```

**Comment by lolmaus** [comment]
Please. 🙏

**Comment by lolmaus** [comment]
Can you at least make it not mark every `foo += bar;` line as an error which you can't fix other than by disabling the rule?

**Comment by elmbank** [comment]
I raised a PR that (hopefully) resolves this issue :)

**Comment by lolmaus** [comment]
And it's already merged, awesome!

Thank you, @elmbank and @lucasefe! 🙇‍♂️

@lucasefe Do you plan releasing soon?

**Comment by lucasefe** [comment]
@lolmaus already did, 1.1.0 is out. 

@elmbank thank you for dedicating time. I really appreciate it.

**Comment by elmbank** [comment]
@lucasefe no problem! :) Thank you for making this nice plugin! Happy to contribute! :D
